## Numpy
- NumPy is a fundamental library for scientific computing in Python. It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures. In this lesson, we will cover the basics of NumPy, focusing on arrays and vectorized operations.

In [2]:
!pip install numpy

In [9]:
import numpy as np

# Creates array using numpy
# 1-D array
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)


[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [12]:
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5)

array([[1, 2, 3, 4, 5]])

In [14]:
# 2-D array
arr2 = np.array([[1,2,3,4,5],[3,4,5,6,7]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [3 4 5 6 7]]
(2, 5)


In [16]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [19]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
np.zeros((5,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

- Identity matrix: Diagonal elements will be one and remaining will be zero.

In [21]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
# Attributes of numpy array
arr = np.array([[1,2,3], [4,5,6]])

print('Array:\n', arr)
print('Shape:', arr.shape)
print('Number of Dimension:', arr.ndim)
print('Size (number of elements)', arr.size)
print('Data type:', arr.dtype)
print('Item size (in bytes):', arr.itemsize)

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of Dimension: 2
Size (number of elements) 6
Data type: int64
Item size (in bytes): 8


- Numpy Vectorized Operation

In [31]:
# Vectorized Operation
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

# Element wise Addition
print("Addition:",arr1 + arr2)

# Element wise substraction
print("Substraction:", arr2 - arr1)

# Element wise multiplication
print("Multiplication:", arr1 * arr2)

# Element wise Division
print("Division:", arr1 / arr2)

Addition: [11 22 33 44 55]
Substraction: [ 9 18 27 36 45]
Multiplication: [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]


- Universal Function

In [36]:
arr = np.array([2,3,4,5,6])

# Square root
print(np.sqrt(arr))

# Exponential
print(np.exp(arr))

# Sine
print(np.sin(arr))

# Natural log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


- Array Slicing and Indexing

In [37]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print('Array : \n', arr)



Array : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [46]:
print(arr[0:2,1:3])
print(arr[1:,2:])

[[2 3]
 [6 7]]
[[ 7  8]
 [11 12]]


In [47]:
arr4 = np.array([[1,2,3,4,5], [6,7,8,9,10], [3,6,3,5,6], [7,8,9,4,3]])
print(arr4)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 3  6  3  5  6]
 [ 7  8  9  4  3]]


In [48]:
print(arr4[1:3,2:4])

[[8 9]
 [3 5]]


In [49]:
# Modify array Elements
arr4[0,0] = 100
print(arr4)

[[100   2   3   4   5]
 [  6   7   8   9  10]
 [  3   6   3   5   6]
 [  7   8   9   4   3]]


In [50]:
arr4[1:] = 100
print(arr4)

[[100   2   3   4   5]
 [100 100 100 100 100]
 [100 100 100 100 100]
 [100 100 100 100 100]]


- Statistical concepts-- Normalization

In [51]:
# Normalization
# to have a mean of 0 and standard deviation of 1

data = np.array([1,2,3,4,5])

# Calculate the mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)

# Normalize the data
normalized_data = (data - mean) / std_dev
print("Normalized data:", normalized_data)

Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [52]:
data = np.array([1,2,3,4,5,6,7,8,9,10])

# Mean 
mean = np.mean(data)
print('Mean:', mean)

# median
median = np.median(data)
print("Median: ", median)

# Standard Deviation
std_dev = np.std(data)
print("Standard Deviation:", std_dev)

# Variance
variance = np.var(data)
print("Variance:", variance)

Mean: 5.5
Median:  5.5
Standard Deviation: 2.8722813232690143
Variance: 8.25


- Logical Operation


In [55]:
data = np.array([1,2,3,4,5,6,7,8,9,10])

data[(data >= 5) & (data <= 8)]

array([5, 6, 7, 8])